"""Adaptive Learning models: per-student LearningPath + per-subject MasteryRecord.

E21 — the `ai_adaptive_learning` plugin (premium, NPR 1499) was sold with a
working service layer (app/services.ai.adaptive_learning) but no storage and
no routes. These tables persist the service output (and teacher overrides) so
`GET /lms/learning-paths` and `GET /lms/adaptive-progress` return real,
tenant-scoped data instead of 404.

Steps are stored as a JSONB list of
  {"title": str, "subject": str|None, "description": str, "status": "pending"|"completed",
   "order": int}
so completion_rate is computed from real per-step status rather than guessed.
"""
from sqlalchemy import (
    Boolean,
    Column,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.models.base import SchoolModel


class LearningPath(SchoolModel):
    """A personalized learning path for one student (or a whole class when
    student_id is NULL). Generated by AdaptiveLearningAI through AITokenHub,
    or created manually by a teacher."""

    __tablename__ = "learning_paths"

    student_id = Column(
        UUID(as_uuid=True), ForeignKey("students.id"), nullable=True, index=True
    )
    class_name = Column(String(120))  # denormalized for class-wide paths + display
    title = Column(String(200), nullable=False)
    subject = Column(String(120))
    difficulty = Column(
        Enum("easy", "medium", "hard", "adaptive", name="learning_path_difficulty"),
        default="adaptive",
    )
    description = Column(Text)
    steps = Column(JSONB, default=list, nullable=False)
    recommended_topics = Column(JSONB, default=list)
    focus_areas = Column(JSONB, default=list)
    resources = Column(JSONB, default=list)
    estimated_hours = Column(Integer)
    # "ai" (LLM via token hub) | "rule_based_fallback" (deterministic, labeled)
    # | "manual" (teacher-created)
    source = Column(String(40), default="manual", nullable=False)
    source_note = Column(String(255))  # honest generator provenance note
    is_active = Column(Boolean, default=True, nullable=False)

    student = relationship("Student", backref="learning_paths")

    @property
    def completion_rate(self):
        """% of steps marked completed (0 when the path has no steps)."""
        steps = self.steps or []
        if not steps:
            return 0
        done = sum(1 for s in steps if (s.get("status") or "pending") == "completed")
        return round(done / len(steps) * 100)

    def to_dict(self):
        student = self.student
        return {
            "id": str(self.id),
            "school_id": str(self.school_id),
            "student_id": str(self.student_id) if self.student_id else None,
            "student_name": (
                f"{student.first_name} {student.last_name}" if student else None
            ),
            "class_name": self.class_name,
            "title": self.title,
            "subject": self.subject,
            "difficulty": self.difficulty,
            "description": self.description,
            "steps": self.steps or [],
            "recommended_topics": self.recommended_topics or [],
            "focus_areas": self.focus_areas or [],
            "resources": self.resources or [],
            "estimated_hours": self.estimated_hours,
            "source": self.source,
            "source_note": self.source_note,
            "is_active": self.is_active,
            "enrolled_count": 1 if self.student_id else 0,
            "completion_rate": self.completion_rate,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class MasteryRecord(SchoolModel):
    """Per (student, subject) mastery level — computed from real Marks by
    AdaptiveLearningAI.assess_mastery, or overridden manually by a teacher."""

    __tablename__ = "mastery_records"
    __table_args__ = (
        UniqueConstraint(
            "school_id", "student_id", "subject", name="uq_mastery_school_student_subject"
        ),
    )

    student_id = Column(
        UUID(as_uuid=True), ForeignKey("students.id"), nullable=False, index=True
    )
    subject = Column(String(120), nullable=False)
    mastery_level = Column(
        Enum("beginner", "intermediate", "advanced", name="mastery_level"),
        default="beginner",
        nullable=False,
    )
    avg_score = Column(Float, default=0.0, nullable=False)
    total_assessments = Column(Integer, default=0, nullable=False)
    # "computed" (service, from Marks) | "manual" (teacher override)
    source = Column(String(40), default="computed", nullable=False)
    notes = Column(Text)

    student = relationship("Student", backref="mastery_records")

    def to_dict(self):
        student = self.student
        return {
            "id": str(self.id),
            "school_id": str(self.school_id),
            "student_id": str(self.student_id),
            "student_name": (
                f"{student.first_name} {student.last_name}" if student else None
            ),
            "subject": self.subject,
            "mastery_level": self.mastery_level,
            "avg_score": float(self.avg_score or 0),
            "total_assessments": self.total_assessments,
            "source": self.source,
            "notes": self.notes,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
