"""Shared WeasyPrint report helpers — letterhead, NPR amounts, Bikram Sambat dates.

This is the canonical pattern for server-side report PDFs, mirroring the fee
receipt (`app/api/v1/fees.py _receipt_pdf_html`) and payslip (`hr_payroll.py`)
conventions: A4 portrait, school letterhead header, NPR money formatting, and
an "Issued" line carrying both AD and Bikram Sambat dates.

All dynamic values passed to :func:`build_report_html` body must already be
HTML-escaped by the caller (use ``markupsafe.escape`` on DB-derived strings).
"""
from datetime import date, datetime

from markupsafe import escape

from app.utils.nepali_date import today_bs


BASE_CSS = """
    @page {
      size: A4;
      margin: 16mm;
      @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9px;
        color: #64748b;
      }
      @bottom-left {
        content: "Generated by ASchool";
        font-size: 9px;
        color: #64748b;
      }
    }
    body { margin: 0; font-family: Arial, sans-serif; color: #0f172a; font-size: 12px; }
    .letterhead { display: flex; justify-content: space-between; gap: 24px;
                  border-bottom: 2px solid #0f172a; padding-bottom: 12px; }
    .school { font-size: 20px; font-weight: 700; }
    .muted { color: #64748b; font-size: 11px; }
    .report-title { text-align: right; }
    .report-title h1 { margin: 0; font-size: 16px; }
    h2.section { font-size: 13px; margin: 18px 0 8px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #e2e8f0; padding: 7px 9px; text-align: left; }
    th { background: #f1f5f9; color: #475569; font-size: 11px; text-transform: uppercase; }
    td.num, th.num { text-align: right; }
    .total-row td { font-weight: 700; background: #f8fafc; }
    .signatures { display: flex; justify-content: space-between; margin-top: 48px; gap: 24px; }
    .sig { flex: 1; border-top: 1px solid #334155; padding-top: 8px; text-align: center;
           color: #475569; font-size: 11px; }
"""


def fmt_npr(amount) -> str:
    """Format an amount as NPR with thousands separators."""
    try:
        value = float(amount or 0)
    except (TypeError, ValueError):
        value = 0.0
    return f"NPR {value:,.2f}"


def school_address_line(school) -> str:
    """Best-effort one-line address for the letterhead."""
    if not school:
        return ""
    parts = [
        getattr(school, "address", None),
        getattr(school, "municipality", None),
        getattr(school, "district", None),
    ]
    text = ", ".join(str(p) for p in parts if p)
    return text


def school_contact_line(school) -> str:
    """Phone / email / PAN line for the letterhead."""
    if not school:
        return ""
    parts = []
    if getattr(school, "phone", None):
        parts.append(f"Phone: {school.phone}")
    if getattr(school, "email", None):
        parts.append(f"Email: {school.email}")
    if getattr(school, "pan_number", None):
        parts.append(f"PAN: {school.pan_number}")
    return " | ".join(escape(str(p)) for p in parts)


def build_report_html(title: str, body_html: str, school=None, subtitle: str = "") -> str:
    """Wrap a pre-escaped ``body_html`` in the letterhead document chrome."""
    school_name = escape(school.name) if school and school.name else "ASchool"
    address_line = escape(school_address_line(school))
    contact_line = school_contact_line(school)
    issued_ad = datetime.now().strftime("%Y-%m-%d")
    issued_line = (
        f"Issued: {escape(issued_ad)} AD &nbsp;|&nbsp; {escape(today_bs())} BS"
    )
    subtitle_html = f'<div class="muted">{escape(subtitle)}</div>' if subtitle else ""
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>{BASE_CSS}</style>
</head>
<body>
  <div class="letterhead">
    <div>
      <div class="school">{school_name}</div>
      <div class="muted">{address_line}</div>
      <div class="muted">{contact_line}</div>
    </div>
    <div class="report-title">
      <h1>{escape(title)}</h1>
      {subtitle_html}
      <div class="muted">{issued_line}</div>
    </div>
  </div>
  {body_html}
  <div class="signatures">
    <div class="sig">Prepared By</div>
    <div class="sig">Account Section</div>
    <div class="sig">Principal</div>
  </div>
</body>
</html>"""


def render_report_pdf(html: str) -> bytes:
    """Render HTML to PDF bytes via WeasyPrint.

    Raises ImportError when WeasyPrint is unavailable (callers should map that
    to a 501, mirroring the fees receipt endpoint).
    """
    from weasyprint import HTML

    return HTML(string=html).write_pdf()
