"""Add Expense and ExpenseCategory models

Revision ID: 28636966600d
Revises: b7e2a1f3c849
Create Date: 2026-04-26 06:45:30.191904
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28636966600d'
down_revision: Union[str, None] = 'b7e2a1f3c849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_categories_school_id'), 'expense_categories', ['school_id'], unique=False)
    op.create_table('expenses',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_school_id'), 'expenses', ['school_id'], unique=False)
    op.alter_column('ai_school_quotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_school_quotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ai_school_quotas_school', table_name='ai_school_quotas')
    op.drop_constraint('uq_ai_school_quotas_school_id', 'ai_school_quotas', type_='unique')
    op.create_index(op.f('ix_ai_school_quotas_school_id'), 'ai_school_quotas', ['school_id'], unique=False)
    op.drop_constraint('ai_school_quotas_school_id_fkey', 'ai_school_quotas', type_='foreignkey')
    op.create_foreign_key(None, 'ai_school_quotas', 'schools', ['school_id'], ['id'])
    op.alter_column('ai_usage_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_usage_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_ai_usage_feature', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_school_date', table_name='ai_usage_logs')
    op.drop_index('idx_ai_usage_user', table_name='ai_usage_logs')
    op.create_index(op.f('ix_ai_usage_logs_feature'), 'ai_usage_logs', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_school_id'), 'ai_usage_logs', ['school_id'], unique=False)
    op.alter_column('designer_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('designer_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_designer_docs_school', table_name='designer_documents')
    op.create_index(op.f('ix_designer_documents_school_id'), 'designer_documents', ['school_id'], unique=False)
    op.drop_constraint('designer_documents_school_id_fkey', 'designer_documents', type_='foreignkey')
    op.create_foreign_key(None, 'designer_documents', 'schools', ['school_id'], ['id'])
    op.add_column('exams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('exams', sa.Column('academic_year_id', sa.UUID(), nullable=True))
    op.add_column('exams', sa.Column('class_ids', sa.ARRAY(sa.UUID()), nullable=True))
    op.add_column('exams', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('exams', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('exams', sa.Column('full_marks', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exams', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'exams', 'academic_years', ['academic_year_id'], ['id'])
    op.alter_column('file_folders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_folders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_file_folders_is_deleted', table_name='file_folders')
    op.drop_constraint('file_folders_school_id_fkey', 'file_folders', type_='foreignkey')
    op.create_foreign_key(None, 'file_folders', 'schools', ['school_id'], ['id'])
    op.add_column('marks', sa.Column('class_id', sa.UUID(), nullable=True))
    op.add_column('marks', sa.Column('entered_by', sa.UUID(), nullable=True))
    op.add_column('marks', sa.Column('obtained_marks', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('marks', sa.Column('full_marks', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('marks', sa.Column('pass_marks', sa.Numeric(precision=6, scale=2), nullable=True))
    op.create_foreign_key(None, 'marks', 'users', ['entered_by'], ['id'])
    op.create_foreign_key(None, 'marks', 'classes', ['class_id'], ['id'])
    op.add_column('report_cards', sa.Column('total_marks', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('report_cards', sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('report_cards', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_cards', 'rank')
    op.drop_column('report_cards', 'percentage')
    op.drop_column('report_cards', 'total_marks')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_column('marks', 'pass_marks')
    op.drop_column('marks', 'full_marks')
    op.drop_column('marks', 'obtained_marks')
    op.drop_column('marks', 'entered_by')
    op.drop_column('marks', 'class_id')
    op.drop_constraint(None, 'file_folders', type_='foreignkey')
    op.create_foreign_key('file_folders_school_id_fkey', 'file_folders', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_file_folders_is_deleted', 'file_folders', ['is_deleted'], unique=False)
    op.alter_column('file_folders', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('file_folders', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'created_by')
    op.drop_column('exams', 'full_marks')
    op.drop_column('exams', 'end_date')
    op.drop_column('exams', 'start_date')
    op.drop_column('exams', 'class_ids')
    op.drop_column('exams', 'academic_year_id')
    op.drop_column('exams', 'instructions')
    op.drop_column('exams', 'description')
    op.drop_constraint(None, 'designer_documents', type_='foreignkey')
    op.create_foreign_key('designer_documents_school_id_fkey', 'designer_documents', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_designer_documents_school_id'), table_name='designer_documents')
    op.create_index('idx_designer_docs_school', 'designer_documents', ['school_id', sa.text('updated_at DESC')], unique=False)
    op.alter_column('designer_documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('designer_documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_usage_logs_school_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_feature'), table_name='ai_usage_logs')
    op.create_index('idx_ai_usage_user', 'ai_usage_logs', ['user_id'], unique=False)
    op.create_index('idx_ai_usage_school_date', 'ai_usage_logs', ['school_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_ai_usage_feature', 'ai_usage_logs', ['feature'], unique=False)
    op.alter_column('ai_usage_logs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_usage_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'ai_school_quotas', type_='foreignkey')
    op.create_foreign_key('ai_school_quotas_school_id_fkey', 'ai_school_quotas', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_school_quotas_school_id'), table_name='ai_school_quotas')
    op.create_unique_constraint('uq_ai_school_quotas_school_id', 'ai_school_quotas', ['school_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_ai_school_quotas_school', 'ai_school_quotas', ['school_id'], unique=False)
    op.alter_column('ai_school_quotas', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_school_quotas', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_expenses_school_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_expense_categories_school_id'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
