"""add iemis and files tables

Revision ID: 4a2c369d23ed
Revises: c1f55f2f9905
Create Date: 2026-04-23 15:30:33.395370
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a2c369d23ed'
down_revision: Union[str, None] = 'c1f55f2f9905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_events',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('max_attendees', sa.Integer(), nullable=True),
    sa.Column('registration_open', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_events_school_id'), 'alumni_events', ['school_id'], unique=False)
    op.create_table('assets',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('asset_code', sa.String(length=100), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_code')
    )
    op.create_index(op.f('ix_assets_school_id'), 'assets', ['school_id'], unique=False)
    op.create_table('iemis_import_logs',
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.Column('format_code', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_rows', sa.Integer(), nullable=True),
    sa.Column('skipped_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'partial', 'failed', name='iemis_import_status'), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iemis_import_logs_school_id'), 'iemis_import_logs', ['school_id'], unique=False)
    op.create_table('managed_files',
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.Enum('image', 'document', 'video', 'audio', 'spreadsheet', 'other', name='managed_file_type'), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_module', sa.String(length=100), nullable=True),
    sa.Column('linked_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Enum('public', 'private', 'school_only', name='file_visibility'), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_files_school_id'), 'managed_files', ['school_id'], unique=False)
    op.create_table('procurement_requests',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vendor', sa.String(length=300), nullable=True),
    sa.Column('purchase_order_ref', sa.String(length=200), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_requests_school_id'), 'procurement_requests', ['school_id'], unique=False)
    op.create_table('staff_appraisals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_appraisals_school_id'), 'staff_appraisals', ['school_id'], unique=False)
    op.create_table('staff_leaves',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_leaves_school_id'), 'staff_leaves', ['school_id'], unique=False)
    op.create_table('staff_payroll',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('bank_ref', sa.String(length=200), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_payroll_school_id'), 'staff_payroll', ['school_id'], unique=False)
    op.create_table('visitor_appointments',
    sa.Column('visitor_name', sa.String(length=300), nullable=False),
    sa.Column('visitor_phone', sa.String(length=20), nullable=True),
    sa.Column('visitor_email', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_appointments_school_id'), 'visitor_appointments', ['school_id'], unique=False)
    op.create_table('visitors',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('id_type', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('visiting_staff_id', sa.UUID(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['visiting_staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_school_id'), 'visitors', ['school_id'], unique=False)
    op.create_table('asset_audit_logs',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_audit_logs_school_id'), 'asset_audit_logs', ['school_id'], unique=False)
    op.create_table('alumni',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('graduation_year', sa.String(length=10), nullable=True),
    sa.Column('batch', sa.String(length=50), nullable=True),
    sa.Column('current_organization', sa.String(length=300), nullable=True),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('is_mentor', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_school_id'), 'alumni', ['school_id'], unique=False)
    op.create_table('alumni_donations',
    sa.Column('alumni_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_ref', sa.String(length=200), nullable=True),
    sa.Column('donated_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_id'], ['alumni.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_donations_school_id'), 'alumni_donations', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumni_donations_school_id'), table_name='alumni_donations')
    op.drop_table('alumni_donations')
    op.drop_index(op.f('ix_alumni_school_id'), table_name='alumni')
    op.drop_table('alumni')
    op.drop_index(op.f('ix_asset_audit_logs_school_id'), table_name='asset_audit_logs')
    op.drop_table('asset_audit_logs')
    op.drop_index(op.f('ix_visitors_school_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_visitor_appointments_school_id'), table_name='visitor_appointments')
    op.drop_table('visitor_appointments')
    op.drop_index(op.f('ix_staff_payroll_school_id'), table_name='staff_payroll')
    op.drop_table('staff_payroll')
    op.drop_index(op.f('ix_staff_leaves_school_id'), table_name='staff_leaves')
    op.drop_table('staff_leaves')
    op.drop_index(op.f('ix_staff_appraisals_school_id'), table_name='staff_appraisals')
    op.drop_table('staff_appraisals')
    op.drop_index(op.f('ix_procurement_requests_school_id'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    op.drop_index(op.f('ix_managed_files_school_id'), table_name='managed_files')
    op.drop_table('managed_files')
    op.drop_index(op.f('ix_iemis_import_logs_school_id'), table_name='iemis_import_logs')
    op.drop_table('iemis_import_logs')
    op.drop_index(op.f('ix_assets_school_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_alumni_events_school_id'), table_name='alumni_events')
    op.drop_table('alumni_events')
    # ### end Alembic commands ###
