"""Full audit migrations

Revision ID: d6d15267f9b8
Revises: d1e2f3a4b5c6
Create Date: 2026-05-16 09:49:03.506216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d15267f9b8'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_app_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='notification_priority'), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_app_notifications_is_read'), 'in_app_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_in_app_notifications_school_id'), 'in_app_notifications', ['school_id'], unique=False)
    op.create_unique_constraint('uq_attendance_student_date', 'attendance', ['school_id', 'student_id', 'date'])
    op.add_column('fee_receipts', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_fee_receipts_idempotency_key'), 'fee_receipts', ['idempotency_key'], unique=True)
    op.create_unique_constraint('uq_teacher_attendance_user_date', 'teacher_attendance', ['school_id', 'user_id', 'date'])
    op.add_column('users', sa.Column('onesignal_player_ids', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onesignal_player_ids')
    op.drop_constraint('uq_teacher_attendance_user_date', 'teacher_attendance', type_='unique')
    op.drop_index(op.f('ix_fee_receipts_idempotency_key'), table_name='fee_receipts')
    op.drop_column('fee_receipts', 'idempotency_key')
    op.drop_constraint('uq_attendance_student_date', 'attendance', type_='unique')
    op.drop_index(op.f('ix_in_app_notifications_school_id'), table_name='in_app_notifications')
    op.drop_index(op.f('ix_in_app_notifications_is_read'), table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    # ### end Alembic commands ###
